FROM ubuntu:22.04

RUN apt update && apt install -y \
    python3-pip cmake g++ git

RUN pip install conan

WORKDIR /app
COPY . .

RUN conan profile detect --force

RUN rm -rf build

RUN conan install . \
    --output-folder=build \
    --build=missing \
    -s build_type=Release

RUN cmake -B build -S . \
    -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Release

RUN cmake --build build

CMD ["bash", "-c", "cd build && ctest --output-on-failure"]